name: Issue Parser Workflow

# Add permissions block at workflow level
permissions:
  issues: write
  contents: read

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  parse-issue:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.issue.state, 'closed') }}

    steps:
      - name: Debug Info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Issue labels: ${{ toJSON(github.event.issue.labels) }}"
          echo "Issue state: ${{ github.event.issue.state }}"

      - name: Check Conditions
        id: check
        run: |
          HAS_ENV_LABEL=$(echo '${{ toJSON(github.event.issue.labels) }}' | jq 'any(.name == "environment")')
          echo "Has environment label: $HAS_ENV_LABEL"
          echo "has_env_label=$HAS_ENV_LABEL" >> $GITHUB_OUTPUT
          echo "issue_state=${{ github.event.issue.state }}" >> $GITHUB_OUTPUT

      - name: Checkout code
        if: steps.check.outputs.has_env_label == 'true'
        uses: actions/checkout@v4

      - name: Process configuration
        if: steps.check.outputs.has_env_label == 'true'
        id: process
        uses: ./.github/actions/process-config
        with:
          issue-body: ${{ github.event.issue.body }}
          issue-title: ${{ github.event.issue.title }}
          issue-number: ${{ github.event.issue.number }}
          trigger-type: ${{ github.event.action }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get previous config
        if: |
          steps.check.outputs.has_env_label == 'true' &&
          github.event.action == 'edited'
        uses: peter-evans/find-comment@v3.1.0
        id: previous-config
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: "github-actions[bot]"
          body-includes: "<!-- CONFIG_HASH="

      - name: Check config changes
        if: |
          steps.check.outputs.has_env_label == 'true' &&
          github.event.action == 'edited'
        id: check-changes
        uses: actions/github-script@v7
        with:
          script: |
            try {
              // Check if previous comment exists
              const hasComment = '${{ steps.previous-config.outputs.comment-id }}' !== '';
              if (!hasComment) {
                console.log('No previous configuration found, treating as new configuration');
                core.setOutput('values_changed', 'true');
                return;
              }

              const previousComment = `${{ steps.previous-config.outputs.comment-body }}`;
              if (!previousComment) {
                console.log('Previous comment body is empty, treating as new configuration');
                core.setOutput('values_changed', 'true');
                return;
              }

              // Extract hash using string operations
              const hashStart = previousComment.indexOf('CONFIG_HASH=');
              if (hashStart === -1) {
                console.log('No hash found in previous comment, treating as new configuration');
                core.setOutput('values_changed', 'true');
                return;
              }

              const hashStartPos = hashStart + 12; // length of 'CONFIG_HASH='
              const hashEnd = previousComment.indexOf(' -->', hashStartPos);
              if (hashEnd === -1) {
                console.log('Invalid hash format in previous comment, treating as new configuration');
                core.setOutput('values_changed', 'true');
                return;
              }

              const previousHash = previousComment.substring(hashStartPos, hashEnd);
              const currentHash = '${{ steps.process.outputs.config-hash }}';

              console.log('Previous hash:', previousHash);
              console.log('Current hash:', currentHash);

              if (!previousHash || !currentHash) {
                console.log('Missing hash values, treating as changed');
                core.setOutput('values_changed', 'true');
                return;
              }

              const valuesChanged = previousHash !== currentHash;
              console.log('Values changed:', valuesChanged);

              core.setOutput('values_changed', valuesChanged.toString());
            } catch (error) {
              console.error('Error in check config changes:', error);
              // Log detailed error information
              console.log('Error details:', {
                hasCommentId: '${{ steps.previous-config.outputs.comment-id }}' !== '',
                commentBody: Boolean('${{ steps.previous-config.outputs.comment-body }}'),
                currentHash: Boolean('${{ steps.process.outputs.config-hash }}')
              });
              // Treat any error as a change to ensure processing continues
              core.setOutput('values_changed', 'true');
            }

      - name: Add guidance comment
        if: |
          steps.check.outputs.has_env_label == 'true' &&
          github.event.action == 'edited' &&
          steps.check-changes.outputs.values_changed == 'false' &&
          steps.previous-config.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## ℹ️ No Changes Detected

            No changes were detected in your configuration values. To retrigger the processing:
            1. Add a comment with the following content:            ```
            /reprocess            ```
            2. Or make changes to your configuration values and save.

            Current configuration:            ```json
            ${{ steps.process.outputs.config-json }}            ```
          reactions: "eyes"

      - name: Add final comment and close issue
        if: |
          steps.check.outputs.has_env_label == 'true' &&
          steps.process.outputs.is-valid == 'true' &&
          (github.event.action != 'edited' || steps.check-changes.outputs.values_changed == 'true')
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## ✅ Configuration Processing Complete

            Your environment configuration has been successfully processed and applied:

            ```ini
            ${{ steps.process.outputs.vars-content }}
            ```

            This issue will be closed automatically as the configuration has been applied.
            If you need to make changes, please create a new configuration issue.

            <!-- CONFIG_PROCESSED -->
          reactions: "+1"

      - name: Close issue
        if: |
          steps.check.outputs.has_env_label == 'true' &&
          steps.process.outputs.is-valid == 'true' &&
          (github.event.action != 'edited' || steps.check-changes.outputs.values_changed == 'true')
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            Issue solved and close.
