name: Issue Parser Workflow

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  parse-issue:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.issue.labels.*.name, 'environment') &&
      github.event.issue.state != 'closed'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 检查配置是否变更（仅编辑时）
      - name: Get previous config
        if: github.event.action == 'edited'
        uses: peter-evans/find-comment@v3.1.0
        id: previous-config
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- CONFIG_HASH='

      # 处理配置
      - name: Process configuration
        id: process
        uses: ./.github/actions/process-config
        with:
          issue-body: ${{ github.event.issue.body }}
          issue-number: ${{ github.event.issue.number }}
          trigger-type: ${{ github.event.action }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # 检查配置是否变更
      - name: Check config changes
        id: check-changes
        if: github.event.action == 'edited'
        uses: actions/github-script@v7
        with:
          script: |
            const previousComment = '${{ steps.previous-config.outputs.comment-body }}';
            const previousHash = previousComment.match(/<!-- CONFIG_HASH=(.*?) -->/)?.[1];
            const currentHash = '${{ steps.process.outputs.config-hash }}';

            core.setOutput('values_changed', (!previousHash || previousHash !== currentHash).toString());

      # 添加指导信息（如果配置未变更）
      - name: Add guidance comment
        if: |
          github.event.action == 'edited' &&
          steps.check-changes.outputs.values_changed == 'false'
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## ℹ️ No Changes Detected

            No changes were detected in your configuration values. To retrigger the processing:
            1. Add a comment with the following content:
            ```
            /reprocess
            ```
            2. Or make changes to your configuration values and save.

            Current configuration:
            ```json
            ${{ steps.process.outputs.config-json }}
            ```
          reactions: 'eyes'

      # 添加最终评论并关闭 issue
      - name: Add final comment and close issue
        if: |
          steps.process.outputs.is-valid == 'true' &&
          (github.event.action != 'edited' || steps.check-changes.outputs.values_changed == 'true')
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## ✅ Configuration Processing Complete

            Your environment configuration has been successfully processed and applied:
            ```shell
            ${{ steps.process.outputs.vars-content }}
            ```

            This issue will be closed automatically as the configuration has been applied.
            If you need to make changes, please create a new configuration issue.

            <!-- CONFIG_PROCESSED -->
          reactions: "+1"

      - name: Close issue
        if: |
          steps.process.outputs.is-valid == 'true' &&
          (github.event.action != 'edited' || steps.check-changes.outputs.values_changed == 'true')
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: false
